"""
Datos maestros del dominio farmacéutico.
Define PA reales con sus familias, metabolismos e interacciones conocidas.
Estos datos base garantizan que las consultas (a), (c), (d), (e) del TP
tengan resultados clínicamente coherentes.
"""

# ── Principios activos maestros ──────────────────────────────────────────────
# Cada PA tiene datos suficientes para Neo4j (via_metabolismo, enzimas)
# y MongoDB (mecanismo_accion completo)
PRINCIPIOS_ACTIVOS_MAESTROS = [
    # ── Betalactámicos ───────────────────────────────────────────────────────
    {"neo4j_node_id": "pa_amoxicilina",    "nombre": "Amoxicilina",
     "familia": "betalactamico", "via_metabolismo": "renal",
     "enzimas": [],              "vida_media_horas": 1.5,
     "mecanismo": "Inhibe la síntesis de pared celular bacteriana uniéndose a PBPs."},
    {"neo4j_node_id": "pa_clavulanato",    "nombre": "Clavulanato",
     "familia": "betalactamico", "via_metabolismo": "renal",
     "enzimas": [],              "vida_media_horas": 1.0,
     "mecanismo": "Inhibidor irreversible de betalactamasas bacterianas."},
    {"neo4j_node_id": "pa_ampicilina",     "nombre": "Ampicilina",
     "familia": "betalactamico", "via_metabolismo": "renal",
     "enzimas": [],              "vida_media_horas": 1.5,
     "mecanismo": "Inhibe la síntesis de pared celular, espectro ampliado vs amoxicilina."},
    # ── Quinolonas ───────────────────────────────────────────────────────────
    {"neo4j_node_id": "pa_ciprofloxacina", "nombre": "Ciprofloxacina",
     "familia": "quinolona",     "via_metabolismo": "renal",
     "enzimas": ["CYP1A2"],      "vida_media_horas": 4.0,
     "mecanismo": "Inhibe ADN girasa y topoisomerasa IV bacteriana."},
    {"neo4j_node_id": "pa_levofloxacina",  "nombre": "Levofloxacina",
     "familia": "quinolona",     "via_metabolismo": "renal",
     "enzimas": [],              "vida_media_horas": 6.0,
     "mecanismo": "Isómero L de ofloxacina. Mayor actividad vs neumococo."},
    # ── Macrólidos ───────────────────────────────────────────────────────────
    {"neo4j_node_id": "pa_azitromicina",   "nombre": "Azitromicina",
     "familia": "macrolido",     "via_metabolismo": "hepatica",
     "enzimas": ["CYP3A4"],      "vida_media_horas": 68.0,
     "mecanismo": "Inhibe síntesis proteica bacterial uniéndose a subunidad 50S."},
    {"neo4j_node_id": "pa_claritromicina", "nombre": "Claritromicina",
     "familia": "macrolido",     "via_metabolismo": "hepatica",
     "enzimas": ["CYP3A4"],      "vida_media_horas": 5.5,
     "mecanismo": "Inhibe síntesis proteica. Fuerte inhibidor CYP3A4."},
    # ── IECAs ────────────────────────────────────────────────────────────────
    {"neo4j_node_id": "pa_enalapril",      "nombre": "Enalapril",
     "familia": "IECA",          "via_metabolismo": "renal",
     "enzimas": [],              "vida_media_horas": 11.0,
     "mecanismo": "Inhibe la enzima convertidora de angiotensina. Profármaco."},
    {"neo4j_node_id": "pa_lisinopril",     "nombre": "Lisinopril",
     "familia": "IECA",          "via_metabolismo": "renal",
     "enzimas": [],              "vida_media_horas": 12.0,
     "mecanismo": "IECA de acción directa, no es profármaco."},
    {"neo4j_node_id": "pa_ramipril",       "nombre": "Ramipril",
     "familia": "IECA",          "via_metabolismo": "hepatica",
     "enzimas": [],              "vida_media_horas": 13.0,
     "mecanismo": "IECA. Cardioprotector post-IAM con amplia evidencia."},
    # ── ARA2 ─────────────────────────────────────────────────────────────────
    {"neo4j_node_id": "pa_losartan",       "nombre": "Losartán",
     "familia": "ARA2",          "via_metabolismo": "hepatica",
     "enzimas": ["CYP2C9"],      "vida_media_horas": 6.0,
     "mecanismo": "Bloquea receptor AT1 de angiotensina II."},
    {"neo4j_node_id": "pa_valsartan",      "nombre": "Valsartán",
     "familia": "ARA2",          "via_metabolismo": "hepatica",
     "enzimas": [],              "vida_media_horas": 9.0,
     "mecanismo": "Antagonista selectivo AT1. Sin metabolito activo."},
    # ── Estatinas ────────────────────────────────────────────────────────────
    {"neo4j_node_id": "pa_atorvastatina",  "nombre": "Atorvastatina",
     "familia": "estatina",      "via_metabolismo": "hepatica",
     "enzimas": ["CYP3A4"],      "vida_media_horas": 14.0,
     "mecanismo": "Inhibe HMG-CoA reductasa. Reduce síntesis de colesterol hepático."},
    {"neo4j_node_id": "pa_rosuvastatina",  "nombre": "Rosuvastatina",
     "familia": "estatina",      "via_metabolismo": "hepatica",
     "enzimas": ["CYP2C9"],      "vida_media_horas": 19.0,
     "mecanismo": "Estatina hidrofílica. Mínima interacción con CYP3A4."},
    {"neo4j_node_id": "pa_simvastatina",   "nombre": "Simvastatina",
     "familia": "estatina",      "via_metabolismo": "hepatica",
     "enzimas": ["CYP3A4"],      "vida_media_horas": 2.0,
     "mecanismo": "Profármaco, activo como ácido simvastatínico."},
    # ── ISRSs ────────────────────────────────────────────────────────────────
    {"neo4j_node_id": "pa_fluoxetina",     "nombre": "Fluoxetina",
     "familia": "ISRS",          "via_metabolismo": "hepatica",
     "enzimas": ["CYP2D6", "CYP2C9"], "vida_media_horas": 96.0,
     "mecanismo": "Inhibidor selectivo de recaptación de serotonina."},
    {"neo4j_node_id": "pa_sertralina",     "nombre": "Sertralina",
     "familia": "ISRS",          "via_metabolismo": "hepatica",
     "enzimas": ["CYP2D6"],      "vida_media_horas": 26.0,
     "mecanismo": "ISRS. Menos interacciones farmacológicas que fluoxetina."},
    {"neo4j_node_id": "pa_paroxetina",     "nombre": "Paroxetina",
     "familia": "ISRS",          "via_metabolismo": "hepatica",
     "enzimas": ["CYP2D6"],      "vida_media_horas": 21.0,
     "mecanismo": "ISRS. Inhibidor potente CYP2D6. Mayor riesgo de interacciones."},
    # ── Antidiabéticos ───────────────────────────────────────────────────────
    {"neo4j_node_id": "pa_metformina",     "nombre": "Metformina",
     "familia": "biguanida",     "via_metabolismo": "renal",
     "enzimas": [],              "vida_media_horas": 6.0,
     "mecanismo": "Reduce gluconeogénesis hepática. No produce hipoglucemia."},
    {"neo4j_node_id": "pa_glibenclamida",  "nombre": "Glibenclamida",
     "familia": "sulfonilurea",  "via_metabolismo": "hepatica",
     "enzimas": ["CYP2C9"],      "vida_media_horas": 10.0,
     "mecanismo": "Estimula secreción de insulina pancreática. Riesgo de hipoglucemia."},
    # ── AINEs ────────────────────────────────────────────────────────────────
    {"neo4j_node_id": "pa_ibuprofeno",     "nombre": "Ibuprofeno",
     "familia": "AINE",          "via_metabolismo": "hepatica",
     "enzimas": ["CYP2C9"],      "vida_media_horas": 2.0,
     "mecanismo": "Inhibe COX-1 y COX-2 de forma no selectiva."},
    {"neo4j_node_id": "pa_diclofenac",     "nombre": "Diclofenac",
     "familia": "AINE",          "via_metabolismo": "hepatica",
     "enzimas": ["CYP2C9"],      "vida_media_horas": 1.2,
     "mecanismo": "AINE con mayor selectividad COX-2 que ibuprofeno."},
    {"neo4j_node_id": "pa_naproxeno",      "nombre": "Naproxeno",
     "familia": "AINE",          "via_metabolismo": "hepatica",
     "enzimas": ["CYP2C9"],      "vida_media_horas": 14.0,
     "mecanismo": "AINE de vida media larga. Buena tolerancia gastrointestinal."},
    # ── Anticoagulantes / antiagregantes ────────────────────────────────────
    {"neo4j_node_id": "pa_warfarina",      "nombre": "Warfarina",
     "familia": "anticoagulante","via_metabolismo": "hepatica",
     "enzimas": ["CYP2C9", "CYP3A4"], "vida_media_horas": 40.0,
     "mecanismo": "Inhibe la epóxido reductasa de vitamina K. Estrecho margen terapéutico."},
    {"neo4j_node_id": "pa_clopidogrel",    "nombre": "Clopidogrel",
     "familia": "antiagregante", "via_metabolismo": "hepatica",
     "enzimas": ["CYP2C19"],     "vida_media_horas": 8.0,
     "mecanismo": "Profármaco. Inhibe receptor P2Y12 plaquetario de forma irreversible."},
    {"neo4j_node_id": "pa_aspirina",       "nombre": "Ácido acetilsalicílico",
     "familia": "antiagregante", "via_metabolismo": "hepatica",
     "enzimas": [],              "vida_media_horas": 0.25,
     "mecanismo": "Acetila COX-1 plaquetaria de forma irreversible. AINE a dosis altas."},
    # ── Opioides ────────────────────────────────────────────────────────────
    {"neo4j_node_id": "pa_tramadol",       "nombre": "Tramadol",
     "familia": "opioide",       "via_metabolismo": "hepatica",
     "enzimas": ["CYP2D6", "CYP3A4"], "vida_media_horas": 6.0,
     "mecanismo": "Agonista opioide débil + inhibición de recaptación de serotonina y NA."},
    {"neo4j_node_id": "pa_morfina",        "nombre": "Morfina",
     "familia": "opioide",       "via_metabolismo": "hepatica",
     "enzimas": [],              "vida_media_horas": 3.0,
     "mecanismo": "Agonista µ-opioide de referencia. Metabolismo por glucuronidación."},
    # ── Corticoides ──────────────────────────────────────────────────────────
    {"neo4j_node_id": "pa_prednisona",     "nombre": "Prednisona",
     "familia": "corticoide",    "via_metabolismo": "hepatica",
     "enzimas": ["CYP3A4"],      "vida_media_horas": 3.5,
     "mecanismo": "Profármaco de prednisolona. Antiinflamatorio e inmunosupresor."},
    {"neo4j_node_id": "pa_dexametasona",   "nombre": "Dexametasona",
     "familia": "corticoide",    "via_metabolismo": "hepatica",
     "enzimas": ["CYP3A4"],      "vida_media_horas": 36.0,
     "mecanismo": "Corticoide fluorado de alta potencia y larga acción."},
    # ── Broncodilatadores ───────────────────────────────────────────────────
    {"neo4j_node_id": "pa_salbutamol",     "nombre": "Salbutamol",
     "familia": "broncodilatador","via_metabolismo": "hepatica",
     "enzimas": [],              "vida_media_horas": 3.8,
     "mecanismo": "Agonista beta-2 adrenérgico de acción corta (SABA)."},
    {"neo4j_node_id": "pa_salmeterol",     "nombre": "Salmeterol",
     "familia": "broncodilatador","via_metabolismo": "hepatica",
     "enzimas": ["CYP3A4"],      "vida_media_horas": 5.5,
     "mecanismo": "Agonista beta-2 de acción prolongada (LABA). Uso en EPOC y asma."},
    # ── Inmunosupresores ────────────────────────────────────────────────────
    {"neo4j_node_id": "pa_ciclosporina",   "nombre": "Ciclosporina",
     "familia": "inmunosupresor","via_metabolismo": "hepatica",
     "enzimas": ["CYP3A4"],      "vida_media_horas": 19.0,
     "mecanismo": "Inhibe calcineurina. Suprime activación de linfocitos T."},
    {"neo4j_node_id": "pa_tacrolimus",     "nombre": "Tacrolimus",
     "familia": "inmunosupresor","via_metabolismo": "hepatica",
     "enzimas": ["CYP3A4"],      "vida_media_horas": 12.0,
     "mecanismo": "Inhibidor de calcineurina. Más potente que ciclosporina."},
    {"neo4j_node_id": "pa_metotrexato",    "nombre": "Metotrexato",
     "familia": "inmunosupresor","via_metabolismo": "renal",
     "enzimas": [],              "vida_media_horas": 10.0,
     "mecanismo": "Antagonista de folato. Inhibe dihidrofolato reductasa."},
    # ── Bifosfonatos ─────────────────────────────────────────────────────────
    {"neo4j_node_id": "pa_alendronato",    "nombre": "Alendronato",
     "familia": "bifosfonato",   "via_metabolismo": "renal",
     "enzimas": [],              "vida_media_horas": 2.0,
     "mecanismo": "Inhibe resorción ósea osteoclástica. Acumulación en hueso."},
]

# ── Interacciones farmacológicas conocidas ───────────────────────────────────
# Pares de PA con tipo, severidad y mecanismo real
# Estas son las que garantizan resultados en consultas (a)(c)(d)(e)
INTERACCIONES_MAESTRAS = [
    # Contraindicadas
    {"pa1": "pa_warfarina",    "pa2": "pa_aspirina",
     "tipo": "potenciacion",  "severidad": "contraindicada",
     "mecanismo": "Ambos inhiben agregación plaquetaria y coagulación. Alto riesgo de sangrado mayor.",
     "evidencia": "meta_analisis"},
    {"pa1": "pa_warfarina",    "pa2": "pa_ibuprofeno",
     "tipo": "potenciacion",  "severidad": "contraindicada",
     "mecanismo": "Ibuprofeno desplaza warfarina de proteínas plasmáticas e inhibe COX-1 plaquetaria.",
     "evidencia": "meta_analisis"},
    {"pa1": "pa_warfarina",    "pa2": "pa_fluoxetina",
     "tipo": "potenciacion",  "severidad": "contraindicada",
     "mecanismo": "Fluoxetina inhibe CYP2C9, aumentando concentración de warfarina hasta 3x.",
     "evidencia": "ensayo_clinico"},
    {"pa1": "pa_warfarina",    "pa2": "pa_claritromicina",
     "tipo": "potenciacion",  "severidad": "contraindicada",
     "mecanismo": "Claritromicina inhibe CYP3A4, reduciendo metabolismo de warfarina.",
     "evidencia": "caso_reporte"},
    {"pa1": "pa_metotrexato",  "pa2": "pa_amoxicilina",
     "tipo": "toxicidad",     "severidad": "contraindicada",
     "mecanismo": "Amoxicilina reduce excreción renal de metotrexato, elevando su concentración a niveles tóxicos.",
     "evidencia": "caso_reporte"},
    {"pa1": "pa_metotrexato",  "pa2": "pa_ibuprofeno",
     "tipo": "toxicidad",     "severidad": "contraindicada",
     "mecanismo": "AINEs reducen eliminación renal de metotrexato. Riesgo de mielotoxicidad fatal.",
     "evidencia": "meta_analisis"},
    {"pa1": "pa_ciclosporina", "pa2": "pa_claritromicina",
     "tipo": "toxicidad",     "severidad": "contraindicada",
     "mecanismo": "Claritromicina inhibe CYP3A4. Niveles de ciclosporina aumentan 3-5x. Nefrotoxicidad.",
     "evidencia": "ensayo_clinico"},
    {"pa1": "pa_tramadol",     "pa2": "pa_fluoxetina",
     "tipo": "toxicidad",     "severidad": "contraindicada",
     "mecanismo": "Ambos elevan serotonina. Síndrome serotoninérgico potencialmente fatal.",
     "evidencia": "meta_analisis"},
    {"pa1": "pa_tramadol",     "pa2": "pa_paroxetina",
     "tipo": "toxicidad",     "severidad": "contraindicada",
     "mecanismo": "Paroxetina inhibe CYP2D6 bloqueando activación de tramadol y elevando serotonina.",
     "evidencia": "ensayo_clinico"},
    # Graves
    {"pa1": "pa_atorvastatina","pa2": "pa_claritromicina",
     "tipo": "toxicidad",     "severidad": "grave",
     "mecanismo": "Claritromicina inhibe CYP3A4, aumentando niveles de atorvastatina. Riesgo de miopatía.",
     "evidencia": "ensayo_clinico"},
    {"pa1": "pa_simvastatina", "pa2": "pa_claritromicina",
     "tipo": "toxicidad",     "severidad": "grave",
     "mecanismo": "Simvastatina es sustrato de CYP3A4. Claritromicina eleva AUC hasta 10x. Rabdomiólisis.",
     "evidencia": "meta_analisis"},
    {"pa1": "pa_simvastatina", "pa2": "pa_ciclosporina",
     "tipo": "toxicidad",     "severidad": "grave",
     "mecanismo": "Ciclosporina inhibe CYP3A4 y OATP1B1. Exposición a simvastatina aumenta 8x.",
     "evidencia": "ensayo_clinico"},
    {"pa1": "pa_atorvastatina","pa2": "pa_ciclosporina",
     "tipo": "toxicidad",     "severidad": "grave",
     "mecanismo": "Ciclosporina inhibe transportadores hepáticos. AUC de atorvastatina aumenta 7x.",
     "evidencia": "ensayo_clinico"},
    {"pa1": "pa_enalapril",    "pa2": "pa_losartan",
     "tipo": "potenciacion",  "severidad": "grave",
     "mecanismo": "Doble bloqueo del SRAA. Hiperpotasemia, hipotensión severa e insuficiencia renal.",
     "evidencia": "meta_analisis"},
    {"pa1": "pa_enalapril",    "pa2": "pa_valsartan",
     "tipo": "potenciacion",  "severidad": "grave",
     "mecanismo": "Doble bloqueo del SRAA. Combinación contraindicada en pacientes con diabetes o renal.",
     "evidencia": "meta_analisis"},
    {"pa1": "pa_enalapril",    "pa2": "pa_ibuprofeno",
     "tipo": "antagonismo",   "severidad": "grave",
     "mecanismo": "AINEs antagonizan efecto antihipertensivo de IECA y pueden causar insuficiencia renal.",
     "evidencia": "meta_analisis"},
    {"pa1": "pa_clopidogrel",  "pa2": "pa_ibuprofeno",
     "tipo": "antagonismo",   "severidad": "grave",
     "mecanismo": "Ibuprofeno bloquea el sitio de acetilación de COX-1, antagonizando el efecto antiagregante.",
     "evidencia": "ensayo_clinico"},
    {"pa1": "pa_warfarina",    "pa2": "pa_diclofenac",
     "tipo": "potenciacion",  "severidad": "grave",
     "mecanismo": "Diclofenac inhibe CYP2C9 y bloquea COX-1 plaquetaria. Riesgo de sangrado digestivo.",
     "evidencia": "meta_analisis"},
    {"pa1": "pa_tramadol",     "pa2": "pa_morfina",
     "tipo": "potenciacion",  "severidad": "grave",
     "mecanismo": "Depresión del SNC aditiva. Riesgo de depresión respiratoria.",
     "evidencia": "consenso_experto"},
    {"pa1": "pa_ciclosporina", "pa2": "pa_tacrolimus",
     "tipo": "toxicidad",     "severidad": "grave",
     "mecanismo": "Ambos inmunosupresores inhiben calcineurina. Nefrotoxicidad aditiva.",
     "evidencia": "ensayo_clinico"},
    # Moderadas
    {"pa1": "pa_atorvastatina","pa2": "pa_azitromicina",
     "tipo": "toxicidad",     "severidad": "moderada",
     "mecanismo": "Azitromicina es inhibidor moderado de CYP3A4. Aumenta leve exposición a atorvastatina.",
     "evidencia": "in_vitro"},
    {"pa1": "pa_metformina",   "pa2": "pa_prednisona",
     "tipo": "antagonismo",   "severidad": "moderada",
     "mecanismo": "Corticoides elevan glucemia, antagonizando el efecto hipoglucemiante de metformina.",
     "evidencia": "ensayo_clinico"},
    {"pa1": "pa_metformina",   "pa2": "pa_dexametasona",
     "tipo": "antagonismo",   "severidad": "moderada",
     "mecanismo": "Dexametasona induce resistencia a insulina y eleva glucemia. Requiere ajuste de dosis.",
     "evidencia": "ensayo_clinico"},
    {"pa1": "pa_ciprofloxacina","pa2": "pa_warfarina",
     "tipo": "potenciacion",  "severidad": "moderada",
     "mecanismo": "Ciprofloxacina inhibe CYP1A2. Puede aumentar INR. Monitorear coagulación.",
     "evidencia": "caso_reporte"},
    {"pa1": "pa_fluoxetina",   "pa2": "pa_tramadol",
     "tipo": "toxicidad",     "severidad": "contraindicada",  # ya está arriba, se filtra en código
     "mecanismo": "duplicado",
     "evidencia": "meta_analisis"},
    {"pa1": "pa_salmeterol",   "pa2": "pa_prednisona",
     "tipo": "sinergismo",    "severidad": "leve",
     "mecanismo": "Combinación estándar en asma/EPOC. Corticoide potencia respuesta broncodilatadora.",
     "evidencia": "meta_analisis"},
    {"pa1": "pa_losartan",     "pa2": "pa_ibuprofeno",
     "tipo": "antagonismo",   "severidad": "grave",
     "mecanismo": "AINEs reducen efectividad de ARA2 y pueden deteriorar función renal.",
     "evidencia": "meta_analisis"},
    {"pa1": "pa_glibenclamida","pa2": "pa_fluoxetina",
     "tipo": "potenciacion",  "severidad": "moderada",
     "mecanismo": "Fluoxetina inhibe CYP2C9, elevando niveles de glibenclamida. Riesgo de hipoglucemia.",
     "evidencia": "caso_reporte"},
    {"pa1": "pa_warfarina",    "pa2": "pa_naproxeno",
     "tipo": "potenciacion",  "severidad": "grave",
     "mecanismo": "Naproxeno desplaza warfarina de proteínas y afecta función plaquetaria.",
     "evidencia": "meta_analisis"},
    {"pa1": "pa_tacrolimus",   "pa2": "pa_claritromicina",
     "tipo": "toxicidad",     "severidad": "contraindicada",
     "mecanismo": "Claritromicina inhibe CYP3A4. Niveles de tacrolimus aumentan hasta 4x. Nefrotoxicidad.",
     "evidencia": "ensayo_clinico"},
]

# ── Patologías para Neo4j ────────────────────────────────────────────────────
PATOLOGIAS = [
    {"nombre": "hipertension_arterial",    "categoria": "cardiovascular", "cie10": "I10"},
    {"nombre": "insuficiencia_cardiaca",   "categoria": "cardiovascular", "cie10": "I50"},
    {"nombre": "fibrilacion_auricular",    "categoria": "cardiovascular", "cie10": "I48"},
    {"nombre": "infarto_miocardio",        "categoria": "cardiovascular", "cie10": "I21"},
    {"nombre": "dislipemia",               "categoria": "metabolismo",    "cie10": "E78"},
    {"nombre": "diabetes_tipo2",           "categoria": "metabolismo",    "cie10": "E11"},
    {"nombre": "diabetes_tipo1",           "categoria": "metabolismo",    "cie10": "E10"},
    {"nombre": "insuficiencia_renal",      "categoria": "renal",          "cie10": "N18"},
    {"nombre": "infeccion_urinaria",       "categoria": "infectologia",   "cie10": "N39"},
    {"nombre": "neumonia",                 "categoria": "respiratorio",   "cie10": "J18"},
    {"nombre": "asma",                     "categoria": "respiratorio",   "cie10": "J45"},
    {"nombre": "EPOC",                     "categoria": "respiratorio",   "cie10": "J44"},
    {"nombre": "depresion",                "categoria": "psiquiatrico",   "cie10": "F32"},
    {"nombre": "ansiedad",                 "categoria": "psiquiatrico",   "cie10": "F41"},
    {"nombre": "artritis_reumatoide",      "categoria": "reumatologia",   "cie10": "M05"},
    {"nombre": "dolor_cronico",            "categoria": "neurologia",     "cie10": "G89"},
    {"nombre": "osteoporosis",             "categoria": "oseo",           "cie10": "M81"},
    {"nombre": "trasplante_renal",         "categoria": "inmunologia",    "cie10": "Z94.0"},
    {"nombre": "hipotiroidismo",           "categoria": "endocrinologia", "cie10": "E03"},
    {"nombre": "epilepsia",               "categoria": "neurologia",     "cie10": "G40"},
    {"nombre": "insuficiencia_hepatica",   "categoria": "hepatica",       "cie10": "K72"},
    {"nombre": "trombosis_venosa",         "categoria": "hematologia",    "cie10": "I80"},
    {"nombre": "psoriasis",                "categoria": "dermatologia",   "cie10": "L40"},
    {"nombre": "esofagitis",              "categoria": "digestivo",      "cie10": "K21"},
    {"nombre": "enfermedad_inflamatoria",  "categoria": "digestivo",      "cie10": "K50"},
    {"nombre": "migraña",                  "categoria": "neurologia",     "cie10": "G43"},
    {"nombre": "gota",                     "categoria": "metabolismo",    "cie10": "M10"},
    {"nombre": "anemia",                   "categoria": "hematologia",    "cie10": "D64"},
    {"nombre": "hiperpotasemia",           "categoria": "metabolismo",    "cie10": "E87.5"},
    {"nombre": "embarazo",                 "categoria": "obstetricia",    "cie10": "Z34"},
]

# ── Relaciones PA-Patología: efectos terapéuticos y adversos ────────────────
AFECTA_MAESTRO = [
    {"pa": "pa_enalapril",     "pat": "hipertension_arterial",  "tipo": "terapeutico"},
    {"pa": "pa_enalapril",     "pat": "insuficiencia_cardiaca",  "tipo": "terapeutico"},
    {"pa": "pa_enalapril",     "pat": "insuficiencia_renal",     "tipo": "adverso"},
    {"pa": "pa_lisinopril",    "pat": "hipertension_arterial",   "tipo": "terapeutico"},
    {"pa": "pa_losartan",      "pat": "hipertension_arterial",   "tipo": "terapeutico"},
    {"pa": "pa_atorvastatina", "pat": "dislipemia",              "tipo": "terapeutico"},
    {"pa": "pa_simvastatina",  "pat": "dislipemia",              "tipo": "terapeutico"},
    {"pa": "pa_rosuvastatina", "pat": "dislipemia",              "tipo": "terapeutico"},
    {"pa": "pa_metformina",    "pat": "diabetes_tipo2",          "tipo": "terapeutico"},
    {"pa": "pa_glibenclamida", "pat": "diabetes_tipo2",          "tipo": "terapeutico"},
    {"pa": "pa_glibenclamida", "pat": "hipoglucemia",            "tipo": "adverso"},
    {"pa": "pa_fluoxetina",    "pat": "depresion",               "tipo": "terapeutico"},
    {"pa": "pa_fluoxetina",    "pat": "ansiedad",                "tipo": "terapeutico"},
    {"pa": "pa_sertralina",    "pat": "depresion",               "tipo": "terapeutico"},
    {"pa": "pa_warfarina",     "pat": "fibrilacion_auricular",   "tipo": "terapeutico"},
    {"pa": "pa_warfarina",     "pat": "trombosis_venosa",        "tipo": "terapeutico"},
    {"pa": "pa_warfarina",     "pat": "embarazo",                "tipo": "contraindicado"},
    {"pa": "pa_salbutamol",    "pat": "asma",                    "tipo": "terapeutico"},
    {"pa": "pa_salmeterol",    "pat": "EPOC",                    "tipo": "terapeutico"},
    {"pa": "pa_prednisona",    "pat": "artritis_reumatoide",     "tipo": "terapeutico"},
    {"pa": "pa_prednisona",    "pat": "diabetes_tipo2",          "tipo": "adverso"},
    {"pa": "pa_ciclosporina",  "pat": "trasplante_renal",        "tipo": "terapeutico"},
    {"pa": "pa_ciclosporina",  "pat": "insuficiencia_renal",     "tipo": "adverso"},
    {"pa": "pa_metotrexato",   "pat": "artritis_reumatoide",     "tipo": "terapeutico"},
    {"pa": "pa_metotrexato",   "pat": "psoriasis",               "tipo": "terapeutico"},
    {"pa": "pa_alendronato",   "pat": "osteoporosis",            "tipo": "terapeutico"},
    {"pa": "pa_alendronato",   "pat": "esofagitis",              "tipo": "adverso"},
    {"pa": "pa_ibuprofeno",    "pat": "dolor_cronico",           "tipo": "terapeutico"},
    {"pa": "pa_ibuprofeno",    "pat": "insuficiencia_renal",     "tipo": "adverso"},
    {"pa": "pa_tramadol",      "pat": "dolor_cronico",           "tipo": "terapeutico"},
    {"pa": "pa_morfina",       "pat": "dolor_cronico",           "tipo": "terapeutico"},
    {"pa": "pa_amoxicilina",   "pat": "neumonia",                "tipo": "terapeutico"},
    {"pa": "pa_amoxicilina",   "pat": "infeccion_urinaria",      "tipo": "terapeutico"},
    {"pa": "pa_ciprofloxacina","pat": "infeccion_urinaria",      "tipo": "terapeutico"},
    {"pa": "pa_clopidogrel",   "pat": "infarto_miocardio",       "tipo": "terapeutico"},
    {"pa": "pa_aspirina",      "pat": "infarto_miocardio",       "tipo": "terapeutico"},
    {"pa": "pa_aspirina",      "pat": "embarazo",                "tipo": "contraindicado"},
]
